### ISSUE TITLE
About how to obtain original pdf files for 2012, 2014

### ISSUE THREAD

**Issue by persistforever** [project-deepform/deepform#103]
Thanks for your repo, it is very meaningful!

I have a question: I want to download the original pdf files and link each pdf with its corresponding labels.

I find that 2020 data is easy to link label with pdf file since you provide the pdf link like this,
![image](https://user-images.githubusercontent.com/9996015/97981689-a36a6880-1e0d-11eb-809b-c02de1b0ed34.png)

However, it is hard to file original pdf files in 2012 and 2014 data.
I can only find the way to link tokenized parquet file with its corresponding labels via file_id.
But, how can I obtain the original pdf files via file_id or other ways?

I find that this file presents the url, but how can I download pdf files with this url?
![image](https://user-images.githubusercontent.com/9996015/97981967-0825c300-1e0e-11eb-9f43-1aa0760c31bf.png)

Thanks!

**Comment by moredatarequired** [comment]
As per the [readme](https://github.com/project-deepform/deepform#where-the-labels-come-from), the 2012 data comes from [ProPublica](https://www.propublica.org/datastore/dataset/free-the-files-filing-data) and the 2014 data from [Alex Byrnes](https://github.com/alexbyrnes/FCC-Political-Ads). We have the token files but not necessarily the PDFs for those two projects.

In theory, all the files are still hosted as part of the [FCC Public File](https://publicfiles.fcc.gov/), and they are searchable and downloadable directly from the FCC.

@andrealowe , do you have more to, or suggestions on how @persistforever could best get the 2012 and 2014 PDFs?

**Comment by moredatarequired** [comment]
Actually, for 2012 it's quite easy, the URLs should be correct in https://github.com/project-deepform/deepform/blob/master/data/2012_manifest.tsv; if they're not correct in the three year manifest perhaps @Gray-Davidson-00 will update the code that produces that.

For 2014 it doesn't appear that https://github.com/project-deepform/deepform/blob/master/data/2014_manifest.tsv has URLs, so my above comment about searching for them in the FCC public file might be the way to go.

**Comment by persistforever** [comment]
thanks！
