### ISSUE TITLE
Match output token more intelligently

### ISSUE THREAD

**Issue by moredatarequired** [project-deepform/deepform#18]
Currently `doc_val_acc` counts as zeros for some answers that are _really_ close to the answers that were volunteer-sourced, such as 
- guessed "$17,925.00" with score 29.85, correct "17,925"
- guessed "$19,850.00" with score 29.67, correct "19850"
- guessed "$25,200.00" with score 29.02, correct "$25,200"
- guessed "$152,900,00" with score 29.15, correct "$152,900.00"

These are all in some sense the same value, but either the volunteer data or the OCRd token are a little bit funny. We should be able to match any of these examples without increasing our false positive rates on tokens that actually disagree about the number.

@jstray discusses some of these issues (and more) in https://app.wandb.ai/deepform/extract_total/reports/What-type-of-errors-does-windowed-total-extraction-make%3F--VmlldzoxMTA4NjE

**Comment by jstray** [comment]
Fixed.
